version: "3.8"
services:
    database-postgres:
        container_name: postgres-container
        image: postgres
        restart: always
        environment:
            - POSTGRES_DB=training_calendar
            - POSTGRES_PASSWORD=123
        ports:
            - "5433:5432"
        expose:
            - 5432

    backend:
        container_name: backend-container
        build:
            context: ../backend
            dockerfile: Dockerfile
        restart: unless-stopped
        environment:
            - DB_PORT=5432
            - DB_HOST=database-postgres
            # - DB_HOST=host.docker.internal
        ports:
            - 8003:8003
    nginx:
        container_name: frontend-container
        build:
            context: ../frontend
        ports:
            - 3000:80
        volumes:
            - ../frontend/build:/usr/share/nginx/html
            - ./default.conf:/etc/nginx/conf.d/default.conf
# docker compose -p training-calendar up -d
